// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DeepComp: typeof import('./src/components/DeepComp.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HmBgCard: typeof import('./src/components/built-in/element-vue2/layout/HmBgCard.vue')['default']
    HmBlock: typeof import('./src/components/HmBlock.vue')['default']
    HmEchartsAreaStack: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsAreaStack.vue')['default']
    HmEchartsBar3DHistogram: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsBar3DHistogram.vue')['default']
    HmEchartsBarSimple: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsBarSimple.vue')['default']
    HmEchartsBarStack: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsBarStack.vue')['default']
    HmEchartsBarYCategoryStack: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsBarYCategoryStack.vue')['default']
    HmEchartsBoxplot: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsBoxplot.vue')['default']
    HmEchartsGauge: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsGauge.vue')['default']
    HmEchartsGaugeStage: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsGaugeStage.vue')['default']
    HmEchartsGeoMap: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsGeoMap.vue')['default']
    HmEchartsLineSimple: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsLineSimple.vue')['default']
    HmEchartsLineStack: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsLineStack.vue')['default']
    HmEchartsPieDoughnut: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsPieDoughnut.vue')['default']
    HmEchartsPieSimple: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsPieSimple.vue')['default']
    HmEchartsRadar: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsRadar.vue')['default']
    HmEchartsWordCloud: typeof import('./src/components/built-in/element-vue2/echarts-vue2/HmEchartsWordCloud.vue')['default']
    HmElementFormily: typeof import('./src/components/built-in/element-vue2/HmElementFormily.vue')['default']
    HmElementTable: typeof import('./src/components/built-in/element-vue2/HmElementTable.vue')['default']
    HmGrid: typeof import('./src/components/built-in/element-vue2/layout/HmGrid.vue')['default']
    HmModal: typeof import('./src/components/built-in/element-vue2/layout/HmModal.vue')['default']
    HmMultiGrid: typeof import('./src/components/built-in/element-vue2/layout/HmMultiGrid.vue')['default']
    HmPanel: typeof import('./src/components/built-in/element-vue2/layout/HmPanel.vue')['default']
    HmTabs: typeof import('./src/components/built-in/element-vue2/layout/HmTabs.vue')['default']
    LastComp: typeof import('./src/components/LastComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }

}
