#!/bin/bash
npm run parse ElButton button/src/button.vue
npm run parse ElAlert alert/src/main.vue
npm run parse ElAvatar avatar/src/main.vue
npm run parse ElBacktop backtop/src/main.vue
npm run parse ElBadge badge/src/main.vue
npm run parse ElBreadcrumb breadcrumb/src/breadcrumb.vue
npm run parse ElCalendar calendar/src/main.vue
npm run parse ElCard card/src/main.vue
npm run parse ElCarousel carousel/src/main.vue
npm run parse ElCascader cascader/src/cascader.vue
npm run parse ElCheckbox checkbox/src/checkbox.vue
npm run parse ElCollapse collapse/src/collapse.vue
npm run parse ElColorPicker color-picker/src/main.vue
npm run parse ElContainer container/src/main.vue
npm run parse ElDatePicker date-picker/src/picker.vue
npm run parse ElDescriptions descriptions/src/index.js
npm run parse ElDialog dialog/src/component.vue
npm run parse ElDivider divider/src/main.vue
npm run parse ElDrawer drawer/src/main.vue
npm run parse ElDropdown dropdown/src/dropdown.vue
npm run parse ElEmpty empty/src/index.vue
npm run parse ElForm form/src/form.vue
npm run parse ElIcon icon/src/icon.vue
npm run parse ElImage image/src/main.vue
npm run parse ElInfiniteScroll infinite-scroll/src/main.js
npm run parse ElInput input/src/input.vue
npm run parse ElInputNumber input-number/src/input-number.vue
npm run parse ElLink link/src/main.vue
npm run parse ElLoading loading/src/loading.vue
npm run parse ElMenu menu/src/menu.vue
npm run parse ElMessage message/src/main.vue
npm run parse ElMessageBox message-box/src/main.vue
npm run parse ElNotification notification/src/main.vue
npm run parse ElPageHeader page-header/src/main.vue
npm run parse ElPagination pagination/src/pager.vue
npm run parse ElPopconfirm popconfirm/src/main.vue
npm run parse ElPopover popover/src/main.vue
npm run parse ElProgress progress/src/progress.vue
npm run parse ElRadio radio/src/radio.vue
npm run parse ElRate rate/src/main.vue
npm run parse ElResult result/src/index.vue
npm run parse ElSelect select/src/select.vue
npm run parse ElSkeleton skeleton/src/index.vue
npm run parse ElSlider slider/src/main.vue